[general]
port = 3030
public = true
domain = "DOMAIN"

[data]
cdclient = "/luclient/res/cdclient.fdb"
locale = "/luclient/locale/locale.xml"
explorer_spa = "/dist"
lu_res_cache = "/cache/lu-res"
lu_json_cache = "/cache/lu-json"
